# -*- coding: utf-8 -*-
"""Atividade introdução a programação - Andares do prédio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBa6-AF6cCPt6fkDhk2lu9lmKOHGyhKe
"""

for andar in range(20, 0, -1):
    if andar != 13:
        print(andar)