# -*- coding: utf-8 -*-
"""Calculadora Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmKTjXBPHi9Ep_R92D84ipjF9SrSJNFO
"""

def calculadora(num1, num2, operacao):

    if operacao == 1:
        return num1 + num2
    elif operacao == 2:
        return num1 - num2
    elif operacao == 3:
        return num1 * num2
    elif operacao == 4:
        if num2 != 0:
            return num1 / num2
        else:
            return "Erro: Divisão por zero"
    else:
        return 0