# -*- coding: utf-8 -*-
"""Calculadora Python melhorada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vmKTjXBPHi9Ep_R92D84ipjF9SrSJNFO
"""

def calculadora():

    while True:
        print("\nEscolha a operação:")
        print("1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        try:
            operacao = int(input("Digite o número correspondente à operação desejada: "))

            if operacao == 0:
                print("Saindo...")
                break
            elif operacao in [1, 2, 3, 4]:
                num1 = float(input("Digite o primeiro número: "))
                num2 = float(input("Digite o segundo número: "))

                if operacao == 1:
                    resultado = num1 + num2
                    print(f"Resultado: {num1} + {num2} = {resultado}")
                elif operacao == 2:
                    resultado = num1 - num2
                    print(f"Resultado: {num1} - {num2} = {resultado}")
                elif operacao == 3:
                    resultado = num1 * num2
                    print(f"Resultado: {num1} * {num2} = {resultado}")
                elif operacao == 4:
                    if num2 != 0:
                        resultado = num1 / num2
                        print(f"Resultado: {num1} / {num2} = {resultado}")
                    else:
                        print("Erro: Divisão por zero não é permitida.")
            else:
                print("Essa opção não existe. Tente novamente.")
        except ValueError:
            print("Entrada inválida. Por favor, digite um número.")

if __name__ == "__main__":
    calculadora()