# -*- coding: utf-8 -*-
"""Calculo idade do usuário

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwTeCIbrHD81CFiDZKq5rwYaAIPcwJyn
"""

def obterAnoNascimento():
    while True:
        try:
            ano = int(input("Digite o ano de nascimento (entre 1922 e 2021): "))
            if 1922 <= ano <= 2021:
                return ano
            else:
                print("Ano fora do intervalo permitido. Por favor, tente novamente.")
        except ValueError:
            print("Entrada inválida. Digite um número...")

def main():
    nome = input("Digite seu nome completo: ")
    anoNascimento = obterAnoNascimento()
    anoAtual = 2022
    idade = anoAtual - anoNascimento

    print(f"{nome}, você completou ou completará {idade} anos em {anoAtual}.")

main()